export const environment = {
  production: true,
  useFakeIam: true,
  platformProviderApiBaseUrl: 'https://reliant-mockapi-ajh4eqgkf7hxg2fx.eastus-01.azurewebsites.net/api/v1',
  platformProviderSignInEndpointPath: '/authentication/sign-in',
  platformProviderSignUpEndpointPath: '/authentication/sign-up',
  platformProviderUsersEndpointPath: '/users',
  platformProviderOrganizationsEndpointPath: '/organizations',
  platformProviderCustomersEndpointPath: '/customers',
  platformProviderComponentsEndpointPath: '/components',
  platformProviderRecuperationsEndpointPath: '/recuperations',
  platformProviderHvofSystemsEndpointPath: '/hvofSystems',
  platformProviderHvofSubsystemsEndpointPath: '/hvofSubsystems',
  platformProviderHvofPartsEndpointPath: '/hvofParts',
  platformProviderControllersEndpointPath: '/controllers',
  platformProviderRecipesEndpointPath: '/recipes',
  platformProviderSpraySessionsEndpointPath: '/spraySessions',
  platformProviderProcessReadingsEndpointPath: '/processReadings',
  platformProviderRolesEndpointPath: '/roles',
  platformProviderPlansEndpointPath: '/plans',
  platformProviderSubscriptionsEndpointPath: '/subscriptions'
};
